### ISSUE TITLE
XINDEX tests are failing in Python 2

### ISSUE THREAD

**Issue by BetsyMcPhail** [WorldVistA/VistA#182]
```
   All Routines? No => No
161:
161:
161:
161:   Routine:
161:
161:   Traceback (most recent call last):
161:
161:     File "C:/Users/betsy.mcphail/development/VistA-Build/Testing/XINDEX/SurgeryTest.py", line 47, in <module>
161:       VistA.write(prefix + '*')
161:     File "C:/Users/betsy.mcphail/development/VistA/Python/vista\OSEHRAHelper.py", line 199, in write
161:       self.connection.write(encode(command) + encode('\r'))
161:     File "C:\Python27\lib\telnetlib.py", line 280, in write
161:       if IAC in buffer:
161:     File "C:\Users\betsy.mcphail\AppData\Roaming\Python\Python27\site-packages\future\types\newstr.py", line 127, in __contains__
161:       newkey = newstr(key)
161:     File "C:\Users\betsy.mcphail\AppData\Roaming\Python\Python27\site-packages\future\types\newstr.py", line 102, in __new__
161:       return super(newstr, cls).__new__(cls, value)
161:
161:   UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0:
161:   ordinal not in range(128)

```

**Comment by shabiel** [comment]
Not supporting Python2 anymore.
