### ISSUE TITLE
Import script failing in Python 2

### ISSUE THREAD

**Issue by BetsyMcPhail** [WorldVistA/VistA#183]
```
$ cmake -P Testing/Setup/ImportRG.cmake
-- Stopping cache instance CACHE
-- Replacing C:/InterSystems/Cache/mgr/VistA/CACHE.DAT
-- Starting cache instance CACHE
-- Preparing M Components...
Looking for routines in subdirectories below C:/Users/betsy.mcphail/development/VistA-M
Looking for globals in subdirectories below C:/Users/betsy.mcphail/development/VistA-M
Looking for routines in subdirectories below C:/Users/betsy.mcphail/development/VistA/Scripts
Looking for globals in subdirectories below C:/Users/betsy.mcphail/development/VistA/Scripts
Packing routines into routines.ro file
Done!
Packing global paths into globals.lst file
Done!
-- Importing VistA Routines...
-- Updating the DPTLK7 routine
-- Importing globals...
-- Initializing VistA...
Traceback (most recent call last):
  File "C:/Users/betsy.mcphail/development/VistA-Build/Testing/Setup/Initialize.py", line 56, in <module>
    OSEHRASetup.addMPILocalNumber(VistA)
  File "C:/Users/betsy.mcphail/development/VistA/Python/vista\OSEHRASetup.py", line 179, in addMPILocalNumber
    VistA.write(localNum)
  File "C:/Users/betsy.mcphail/development/VistA/Python/vista\OSEHRAHelper.py", line 199, in write
    self.connection.write(encode(command) + encode('\r'))
  File "C:\Python27\lib\telnetlib.py", line 280, in write
    if IAC in buffer:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
-- Running PostImportSetup script...
Traceback (most recent call last):
  File "C:/Users/betsy.mcphail/development/VistA-Build/Testing/Setup/PostImportSetupScript.py", line 81, in <module>
    OSEHRASetup.setupVistADomain(VistA,"DEMO.OSEHRA.ORG")
  File "C:/Users/betsy.mcphail/development/VistA/Python/vista\OSEHRASetup.py", line 310, in setupVistADomain
    VistA.write('S $P(^XWB(8994.1,1,0),"^")=' + VistA.IENumber)
  File "C:/Users/betsy.mcphail/development/VistA/Python/vista\OSEHRAHelper.py", line 199, in write
    self.connection.write(encode(command) + encode('\r'))
  File "C:\Python27\lib\telnetlib.py", line 280, in write
    if IAC in buffer:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
CMake Error at Testing/Setup/ImportRG.cmake:18 (message):
  ERROR: Post Import Setup Failed
Call Stack (most recent call first):
  Testing/Setup/ImportRG.cmake:118 (CheckResult)

```

**Comment by shabiel** [comment]
Not supporting Python2 anymore.
